import {
  autopsyContent,
  defineCase,
  doc,
  evidence,
  firContent,
  suspect,
  timelineEvent,
  victim,
  witness,
} from "./builder";

/** Inspired by journalist murders and corruption exposé retaliation cases. Fully fictional. */
export const case05LastBroadcast = defineCase(5, {
  meta: {
    id: "case-05-last-broadcast",
    title: "The Last Broadcast",
    crimeType: "Homicide — Gunshot / Staged Scene",
    severity: "critical",
    date: "2026-04-19",
    time: "11:08 PM",
    location: "KANE Studios, 44 Warehouse District",
    difficulty: "hard",
    synopsis:
      "An investigative journalist is shot in her recording booth hours before airing a corruption exposé. Someone wanted the story — and the storyteller — dead.",
    briefing:
      "Rachel Kane, host of true-crime podcast 'Buried Lines,' was found shot in Studio B with a deleted episode on her hard drive. She was preparing to name a city official's fixer in a kickback scheme. Three suspects had access that night. Recover the audio, trace the weapon, and break the alibi.",
    inspiredBy:
      "Inspired by documented retaliation against investigative journalists and corruption whistleblowers. All persons and events are fictional.",
    estimatedMinutes: 60,
    coverImage: "/images/case-05-last-broadcast.png",
  },
  victim: victim({
    id: "victim-kane",
    name: "Rachel Kane",
    age: 36,
    occupation: "Investigative Journalist & Podcast Host",
    background:
      "Former city desk reporter. Spent 8 months on 'Operation Ledger' — municipal contract kickbacks. Episode 47 was final cut.",
    lastSeen: "10:40 PM on studio camera entering Booth B",
    causeOfDeath: "Single .38 caliber gunshot — thoracic, through-and-through",
    injuries: ["Contact-range muzzle burn", "Defensive graze on left palm", "Studio chair overturned"],
  }),
  suspects: [
    suspect({
      id: "suspect-morrow",
      name: "Derek Morrow",
      age: 45,
      occupation: "Political Fixer",
      personality: "Smooth, threatening charm, connected",
      stressLevel: 9,
      intelligence: 9,
      secrets: [
        "Ran kickback network for Councilman Hale",
        "Was on studio roof access list via bribed security",
        "Owned .38 snub registered to shell LLC — reported stolen",
      ],
      fear: "Federal RICO indictment",
      relationships: { "Rachel Kane": "Threatened her March 12", "Councilman Hale": "Employer", "Tyler Shaw": "Paid studio access" },
      financialSituation: "Luxury condo, offshore accounts",
      dailyRoutine: "Meetings by day, 'consulting' by night",
      motive: "Episode 47 named him as bagman — aired in 6 hours",
      alibi: "Claims dinner at Vale Restaurant 9:00–11:30 PM with Hale",
      truthfulness: 2,
      behavior: "Confident, threatens lawsuits",
      speechStyle: "Polished, deflects with humor and menace",
      knowledge: [
        "Knew episode upload deadline was midnight",
        "Bribed Shaw $5K for after-hours access codes",
        "Councilman Hale said 'make it go away' April 17",
      ],
      memory: {},
      isGuilty: true,
    }),
    suspect({
      id: "suspect-shaw",
      name: "Tyler Shaw",
      age: 28,
      occupation: "Studio Engineer",
      personality: "Brilliant, anxious, easily manipulated",
      stressLevel: 8,
      intelligence: 8,
      secrets: ["Sold Morrow access logs for cash", "Heard argument in Booth B at 10:55 PM"],
      fear: "Never working in media again",
      relationships: { "Rachel Kane": "Colleague", "Derek Morrow": "Secret payment" },
      financialSituation: "Student debt, behind on rent",
      dailyRoutine: "Runs boards, handles file exports",
      motive: "Accessory — payment, not instigator",
      alibi: "Claims alone in Master Control editing Episode 46 reruns",
      truthfulness: 5,
      behavior: "Fidgets, overuses technical jargon when nervous",
      speechStyle: "Tech-speak, rapid when stressed",
      knowledge: [
        "Morrow's keycard pinged 10:52 PM — shouldn't have access",
        "Recovered partial auto-save of Episode 47 on backup drive",
        "Rachel changed door code Tuesday — only she and Shaw knew it",
      ],
      memory: {},
      isGuilty: false,
    }),
    suspect({
      id: "suspect-hale",
      name: "Councilman Victor Hale",
      age: 52,
      occupation: "City Council Member",
      personality: "Public saint, private tyrant",
      stressLevel: 7,
      intelligence: 8,
      secrets: ["Signed off on contracts Morrow rigged", "Texted 'handle Kane' to Morrow"],
      fear: "Re-election collapse, federal probe",
      relationships: { "Derek Morrow": "Fixer", "Rachel Kane": "Publicly praised, privately despised" },
      financialSituation: "Campaign war chest, shell donors",
      dailyRoutine: "Council by day, fundraisers by night",
      motive: "Episode implicated him directly in contract steering",
      alibi: "Vale Restaurant dinner with Morrow — maître d' confirms both 9:15–11:45 PM",
      truthfulness: 4,
      behavior: "Performs outrage, cites public service",
      speechStyle: "Political cadence, rehearsed empathy",
      knowledge: ["Didn't know Morrow planned violence", "Episode draft mentioned him 14 times"],
      memory: {},
      isGuilty: false,
    }),
  ],
  witnesses: [
    witness({
      id: "witness-patel",
      name: "Sonia Patel",
      age: 31,
      occupation: "Podcast Producer",
      personality: "Fierce, grieving, detail-oriented",
      stressLevel: 8,
      intelligence: 8,
      secrets: [],
      fear: "Kane's work dying with her",
      relationships: { "Rachel Kane": "Best friend and producer" },
      financialSituation: "Moderate",
      dailyRoutine: "Left studio 8 PM — Rachel stayed to record alone",
      motive: "N/A",
      alibi: "Home by 8:30 PM — rideshare confirms",
      truthfulness: 9,
      behavior: "Emotional but precise about production schedule",
      speechStyle: "Fast, production terminology",
      knowledge: [
        "Episode 47 backup auto-saved to cloud at 10:38 PM",
        "Rachel received threatening text from unknown number April 18",
        "Morrow visited studio lobby April 15 asking about 'schedule'",
      ],
      memory: {},
    }),
  ],
  evidence: [
    evidence({
      id: "ev5-fir",
      title: "First Information Report",
      type: "document",
      description: "Homicide — Kane Studios.",
      locationFound: "Detective Bureau",
      discoveredByDefault: true,
      hidden: false,
      relatedPeople: ["victim-kane"],
      relatedEvidence: [],
      significance: "supporting",
      tags: ["official"],
      documentId: "doc5-fir",
    }),
    evidence({
      id: "ev5-scene",
      title: "Studio B Crime Scene",
      type: "physical",
      description: "Single gunshot from close range. Booth door locked from inside — but emergency exit to alley was propped open.",
      locationFound: "Studio B",
      discoveredByDefault: true,
      hidden: false,
      relatedPeople: ["victim-kane"],
      relatedEvidence: ["ev5-shell", "ev5-exit"],
      significance: "critical",
      tags: ["crime scene"],
      image: "/images/evidence-05-studio.png",
    }),
    evidence({
      id: "ev5-shell",
      title: ".38 Caliber Shell Casing",
      type: "forensic",
      description: "Brass casing by mixing board. Ballistics match snub-nose .38 — same model as Morrow's 'stolen' registered weapon.",
      locationFound: "Studio B floor",
      discoveredByDefault: true,
      hidden: false,
      relatedPeople: ["suspect-morrow"],
      relatedEvidence: ["ev5-ballistics"],
      significance: "critical",
      tags: ["forensic", "weapon"],
    }),
    evidence({
      id: "ev5-ballistics",
      title: "Ballistics Match Report",
      type: "forensic",
      description: "Casing matches test-fired round from Morrow LLC-registered revolver reported stolen Jan 2026.",
      locationFound: "State crime lab",
      discoveredByDefault: false,
      hidden: true,
      unlockCondition: "Submit casing to lab",
      relatedPeople: ["suspect-morrow"],
      relatedEvidence: ["ev5-shell"],
      significance: "critical",
      tags: ["forensic"],
      documentId: "doc5-ballistics",
    }),
    evidence({
      id: "ev5-audio",
      title: "Recovered Episode 47 Audio",
      type: "digital",
      description: "Auto-save captures Rachel saying 'Derek Morrow collected $400K in—' then door opens, struggle, shot. Male voice: 'Not tonight.'",
      locationFound: "Cloud backup / Shaw's recovery",
      discoveredByDefault: false,
      hidden: true,
      unlockCondition: "Interview producer Patel or engineer Shaw",
      relatedPeople: ["suspect-morrow", "victim-kane"],
      relatedEvidence: ["ev5-scene"],
      significance: "critical",
      tags: ["media", "motive"],
      documentId: "doc5-audio",
    }),
    evidence({
      id: "ev5-keycard",
      title: "Keycard Access Log",
      type: "digital",
      description: "Morrow's deactivated consultant badge pinged entry 10:52 PM. Badge reactivated remotely 10:51 PM — Shaw's admin credentials used.",
      locationFound: "Studio security",
      discoveredByDefault: false,
      hidden: true,
      unlockCondition: "Search security logs",
      relatedPeople: ["suspect-morrow", "suspect-shaw"],
      relatedEvidence: ["ev5-payment"],
      significance: "critical",
      tags: ["timeline", "alibi"],
      documentId: "doc5-keycard",
    }),
    evidence({
      id: "ev5-alibi",
      title: "Restaurant Alibi Timeline",
      type: "document",
      description: "Vale Restaurant confirms Morrow + Hale seated 9:15 PM. BUT: Morrow's card charged valet 9:08 PM and 11:38 PM — 38-minute gap unaccounted.",
      locationFound: "Restaurant + card records",
      discoveredByDefault: false,
      hidden: false,
      relatedPeople: ["suspect-morrow", "suspect-hale"],
      relatedEvidence: ["ev5-keycard"],
      significance: "critical",
      tags: ["alibi"],
      documentId: "doc5-alibi",
    }),
    evidence({
      id: "ev5-payment",
      title: "Shaw Cash Payment",
      type: "financial",
      description: "$5,000 cash to Shaw from Morrow shell LLC 'consulting fee' April 17. Memo: 'studio access assistance.'",
      locationFound: "Bank subpoena",
      discoveredByDefault: false,
      hidden: true,
      unlockCondition: "Financial warrant on Shaw",
      relatedPeople: ["suspect-shaw", "suspect-morrow"],
      relatedEvidence: ["ev5-keycard"],
      significance: "important",
      tags: ["financial"],
      documentId: "doc5-payment",
    }),
    evidence({
      id: "ev5-text",
      title: "Hale Text to Morrow",
      type: "digital",
      description: "'Handle Kane before Friday upload. I can't have this out.' April 17, 11:02 PM.",
      locationFound: "Phone warrant — Hale",
      discoveredByDefault: false,
      hidden: true,
      unlockCondition: "Warrant Councilman's phone",
      relatedPeople: ["suspect-hale", "suspect-morrow"],
      relatedEvidence: ["ev5-audio"],
      significance: "important",
      tags: ["motive"],
      documentId: "doc5-text",
    }),
    evidence({
      id: "ev5-exit",
      title: "Alley Exit Propped Open",
      type: "physical",
      description: "Fire exit wedge matches wood from Morrow's condo renovation (sawdust DNA match). Mud on step — size 11 Bruno Magli.",
      locationFound: "Studio alley",
      discoveredByDefault: false,
      hidden: true,
      unlockCondition: "Crime scene secondary sweep",
      relatedPeople: ["suspect-morrow"],
      relatedEvidence: ["ev5-scene"],
      significance: "important",
      tags: ["forensic"],
    }),
    evidence({
      id: "ev5-threat",
      title: "Threatening Text to Kane",
      type: "digital",
      description: "Burner phone text April 18: 'Pull episode 47 or learn what buried really means.' Triangulated near Morrow's office.",
      locationFound: "Telecom subpoena",
      discoveredByDefault: true,
      hidden: false,
      relatedPeople: ["suspect-morrow"],
      relatedEvidence: [],
      significance: "important",
      tags: ["motive"],
      documentId: "doc5-threat",
    }),
  ],
  timeline: [
    timelineEvent({
      id: "tl5-2140",
      timestamp: "2026-04-19 22:40",
      title: "Rachel enters Studio B",
      description: "Camera confirms solo recording session.",
      known: true,
      people: ["victim-kane"],
      evidence: [],
    }),
    timelineEvent({
      id: "tl5-2152",
      timestamp: "2026-04-19 22:52",
      title: "Morrow badge ping",
      description: "Entry logged — restaurant alibi claims he's at Vale.",
      known: false,
      people: ["suspect-morrow"],
      evidence: ["ev5-keycard", "ev5-alibi"],
      conflictWith: ["tl5-dinner"],
    }),
    timelineEvent({
      id: "tl5-dinner",
      timestamp: "2026-04-19 21:15",
      title: "Morrow at Vale Restaurant",
      description: "Maître d' confirms seating with Hale.",
      known: true,
      people: ["suspect-morrow", "suspect-hale"],
      evidence: ["ev5-alibi"],
      conflictWith: ["tl5-2152"],
    }),
    timelineEvent({
      id: "tl5-2155",
      timestamp: "2026-04-19 22:55",
      title: "Argument in Booth B",
      description: "Shaw hears muffled shouting through soundproof glass.",
      known: false,
      people: ["victim-kane", "suspect-morrow"],
      evidence: ["ev5-audio"],
    }),
    timelineEvent({
      id: "tl5-2208",
      timestamp: "2026-04-19 23:08",
      title: "Gunshot — body discovered",
      description: "Shaw enters booth after hearing thud. Calls 911.",
      known: true,
      people: ["victim-kane", "suspect-shaw"],
      evidence: ["ev5-scene", "ev5-shell"],
    }),
  ],
  documents: [
    doc({
      id: "doc5-fir",
      type: "fir",
      title: "First Information Report",
      referenceNumber: "CF-2026-0419-022",
      date: "2026-04-20",
      author: "Det. Sarah Chen",
      content: firContent("The Last Broadcast", "CF-2026-0419-022", {
        complainant: "Tyler Shaw (studio engineer)",
        victim: "Rachel Kane, 36",
        location: "44 Warehouse District, Studio B",
        datetime: "2026-04-19 23:08",
        narrative:
          "Victim shot during solo recording. Episode 47 deleted from primary drive. Political corruption exposé scheduled for midnight release.",
      }),
    }),
    doc({
      id: "doc5-autopsy",
      type: "autopsy",
      title: "Autopsy — Kane",
      referenceNumber: "ME-2026-1522",
      date: "2026-04-20",
      author: "Dr. Elena Marsh",
      content: autopsyContent("Rachel Kane", {
        ref: "ME-2026-1522",
        date: "2026-04-20",
        cause: "Gunshot wound — .38 caliber",
        timeOfDeath: "22:57–23:02 PM",
        findings: [
          "Contact-range muzzle burn on sternum",
          "Defensive graze on left palm — hands up",
          "No drugs or alcohol",
          "Time of death matches audio recording timestamp",
        ],
      }),
      image: "/images/evidence-05-studio.png",
    }),
    doc({
      id: "doc5-ballistics",
      type: "lab_report",
      title: "Ballistics Report",
      referenceNumber: "BAL-2026-331",
      date: "2026-04-21",
      author: "State Crime Lab",
      content: `Casing recovered Studio B
Match: SNUB-38 registered to Morrow Consulting LLC
Weapon status: Reported stolen 01/14/2026
Probability of random match: < 1 in 890,000

HINT: 'Stolen' guns often aren't.`,
      classified: true,
    }),
    doc({
      id: "doc5-audio",
      type: "audio",
      title: "Episode 47 Recovery Transcript",
      referenceNumber: "AUD-2026-047",
      date: "2026-04-21",
      author: "Digital Forensics",
      content: `AUTO-SAVE TIMESTAMP: 22:56:41

RACHEL: "...and the man who collected over four hundred thousand in kickbacks is Derek Mor—"

[SOUND: door opens, chair scrape]

RACHEL: "You can't be in here—"

MALE VOICE: "Not tonight."

[GUNSHOT — recording ends]

Voice stress analysis: 94% match Morrow reference sample.`,
      classified: true,
      image: "/images/evidence-05-studio.png",
    }),
    doc({
      id: "doc5-keycard",
      type: "cctv_log",
      title: "Studio Access Log",
      referenceNumber: "SEC-KANE-0419",
      date: "2026-04-20",
      author: "Building Security",
      content: `22:52:08 — Badge MORROW-D (reactivated 22:51:55 by admin T.SHAW)
22:52:11 — Entry Studio B corridor
23:01:44 — Alley fire exit opened
23:02:19 — Badge exit ping (parking garage)

Restaurant alibi: Morrow valet ticket 21:08 and 23:38`,
      classified: true,
    }),
    doc({
      id: "doc5-alibi",
      type: "investigation_notes",
      title: "Alibi Gap Analysis",
      referenceNumber: "INV-2026-419",
      date: "2026-04-21",
      author: "Det. Sarah Chen",
      content: `Vale Restaurant: Morrow seated 21:15 with Hale
Valet timestamps: 21:08 in, 23:38 out
Studio keycard: 22:52 entry

GAP: 21:08–21:15 (minor) AND 22:30–23:38 (CRITICAL)
Drive Vale → Studio: 12 minutes

Morrow had time to shoot Kane and return to restaurant.`,
    }),
    doc({
      id: "doc5-payment",
      type: "bank_transactions",
      title: "Shaw Payment Record",
      referenceNumber: "BNK-2026-552",
      date: "2026-04-22",
      author: "Financial Crimes",
      content: `Morrow Consulting LLC → Tyler Shaw
Amount: $5,000
Date: April 17, 2026
Memo: "studio access assistance"
Shaw withdrew $4,800 cash April 18`,
      classified: true,
    }),
    doc({
      id: "doc5-text",
      type: "chat_history",
      title: "Hale ↔ Morrow Texts",
      referenceNumber: "TXT-2026-88",
      date: "2026-04-22",
      author: "Warrant Return",
      content: `Apr 17, 23:02 — Hale: "Handle Kane before Friday upload. I can't have this out."
Apr 17, 23:04 — Morrow: "Consider it handled."
Apr 18, 09:15 — Hale: "I meant pressure, Derek. Not—"
Apr 18, 09:16 — Morrow: "You don't want to know."`,
      classified: true,
    }),
    doc({
      id: "doc5-threat",
      type: "phone_records",
      title: "Burner Threat Analysis",
      referenceNumber: "TEL-2026-991",
      date: "2026-04-20",
      author: "Telecom Liaison",
      content: `To: Rachel Kane — Apr 18, 14:22
"Pull episode 47 or learn what buried really means."
Origin: Cell tower 0.3mi from Morrow Consulting office
Burner purchased: Morrow aide's credit card (mislabeled expense)`,
    }),
  ],
  locations: [
    {
      id: "loc5-studio",
      name: "KANE Studios — Booth B",
      address: "44 Warehouse District",
      description: "Soundproof booth, mixing board, blood spatter on acoustic panel.",
      searchable: true,
      unlocked: true,
      evidenceIds: ["ev5-scene", "ev5-shell"],
      coordinates: { x: 48, y: 52 },
    },
    {
      id: "loc5-alley",
      name: "Studio Alley Exit",
      address: "Warehouse District Rear",
      description: "Fire exit, propped door, muddy footprints.",
      searchable: true,
      unlocked: false,
      evidenceIds: ["ev5-exit"],
      coordinates: { x: 65, y: 58 },
    },
    {
      id: "loc5-control",
      name: "Master Control Room",
      address: "KANE Studios",
      description: "Shaw's post. Backup drives, access admin panel.",
      searchable: true,
      unlocked: true,
      evidenceIds: ["ev5-audio", "ev5-keycard"],
      coordinates: { x: 35, y: 48 },
    },
  ],
  policeNotes:
    "Journalist murder with political tentacles. Morrow's restaurant alibi has a 38-minute hole — do the drive time math. Shaw enabled access but the audio names Morrow at the scene. Recover Episode 47 first.",
  redHerrings: ["suspect-hale"],
  hiddenClues: ["ev5-audio", "ev5-ballistics", "ev5-keycard", "ev5-payment", "ev5-exit"],
  evidenceRelationships: [
    { from: "ev5-audio", to: "suspect-morrow", label: "voice at scene", suggested: true },
    { from: "ev5-alibi", to: "ev5-keycard", label: "alibi gap fits", suggested: true },
    { from: "ev5-shell", to: "ev5-ballistics", label: "weapon link", suggested: true },
  ],
  solution: {
    guiltyPartyId: "suspect-morrow",
    method: "Entered studio via reactivated badge, shot Kane during recording, fled through alley",
    motive: "Silence corruption exposé naming him as kickback collector",
    opportunity: "Paid for access codes, gap in restaurant alibi, owned matched weapon",
    requiredEvidence: ["ev5-audio", "ev5-ballistics", "ev5-keycard", "ev5-alibi", "ev5-shell"],
    criticalContradictions: ["tl5-dinner"],
    timelineKey: ["tl5-2152", "tl5-2155", "tl5-2208"],
    charges: ["Murder in the First Degree", "Witness Intimidation", "Obstruction of Justice"],
  },
});
