import {
  autopsyContent,
  defineCase,
  doc,
  evidence,
  firContent,
  suspect,
  timelineEvent,
  victim,
  witness,
} from "./builder";

/** Inspired by real white-collar fraud cases where executives were killed to silence investigations. Fully fictional. */
export const case01MeridianLedger = defineCase(1, {
  meta: {
    id: "case-01-meridian-ledger",
    title: "The Meridian Ledger",
    crimeType: "Homicide — Blunt Force Trauma",
    severity: "high",
    date: "2026-03-14",
    time: "11:47 PM",
    location: "Meridian Tech Parking Structure, Level P3",
    difficulty: "easy",
    synopsis:
      "A startup CFO is found dead beside his car hours before a forensic audit. Someone needed the numbers to die with him.",
    briefing:
      "Daniel Pierce, CFO of Meridian Tech, was discovered unconscious at 11:52 PM on Level P3 of the company garage. Security reports a confrontation. A pending SEC audit threatened to expose irregular transfers. Interview suspects, reconcile the books, and find who had the most to lose.",
    inspiredBy:
      "Inspired by documented patterns in corporate fraud investigations where financial whistleblowers and executives faced lethal retaliation. All names and events are fictional.",
    estimatedMinutes: 35,
    coverImage: "/images/case-01-meridian-ledger.png",
  },
  victim: victim({
    id: "victim-pierce",
    name: "Daniel Pierce",
    age: 44,
    occupation: "Chief Financial Officer, Meridian Tech",
    background:
      "Former Big Four accountant. Known for meticulous records. Had scheduled a meeting with federal auditors for Monday morning.",
    lastSeen: "10:30 PM leaving the executive floor",
    causeOfDeath: "Blunt force trauma to the occipital region",
    injuries: ["Skull fracture", "Defensive bruising on forearms", "Asphalt abrasions on palms"],
  }),
  suspects: [
    suspect({
      id: "suspect-webb",
      name: "Marcus Webb",
      age: 47,
      occupation: "Co-Founder & CEO, Meridian Tech",
      personality: "Charismatic, controlling, image-obsessed",
      stressLevel: 8,
      intelligence: 9,
      secrets: ["Authorized off-book transfers through shell vendors", "Pierce confronted him Friday"],
      fear: "Prison and public humiliation",
      relationships: { "Daniel Pierce": "Business partner — increasingly hostile", "Lena Ortiz": "Ex-wife, still owns shares" },
      financialSituation: "Personally guaranteed loans against company valuation",
      dailyRoutine: "Works late, uses private elevator after 9 PM",
      motive: "Pierce was about to hand auditors proof of embezzlement tied to Webb",
      alibi: "Claims he was on a investor call from his home office 10:00–11:30 PM",
      truthfulness: 3,
      behavior: "Cooperative but deflects to 'company priorities'",
      speechStyle: "Corporate, confident, uses jargon to obscure",
      knowledge: [
        "Knew about the audit deadline",
        "Pierce emailed him a draft disclosure Saturday",
        "Has access to garage master fob",
      ],
      memory: {},
      isGuilty: true,
    }),
    suspect({
      id: "suspect-ortiz",
      name: "Lena Ortiz",
      age: 42,
      occupation: "Venture Capital Partner",
      personality: "Sharp, guarded, strategic",
      stressLevel: 5,
      intelligence: 8,
      secrets: ["Still holds 12% equity via divorce settlement"],
      fear: "Portfolio collapse if Meridian implodes",
      relationships: { "Marcus Webb": "Ex-spouse", "Daniel Pierce": "Professional ally in board disputes" },
      financialSituation: "Wealthy but overexposed to Meridian stock",
      dailyRoutine: "Travels often, was in town for board dinner",
      motive: "Pierce supported her bid to replace Webb as CEO",
      alibi: "Hotel restaurant receipt at 10:45 PM, CCTV at Grand Meridian lobby 11:10 PM",
      truthfulness: 7,
      behavior: "Direct, impatient with repetition",
      speechStyle: "Precise, clipped East Coast finance",
      knowledge: ["Heard Webb and Pierce arguing Wednesday", "Pierce was storing backup files off-site"],
      memory: {},
      isGuilty: false,
    }),
    suspect({
      id: "suspect-klein",
      name: "Ryan Klein",
      age: 29,
      occupation: "Senior Accountant",
      personality: "Anxious, diligent, loyal to Pierce",
      stressLevel: 7,
      intelligence: 7,
      secrets: ["Helped Pierce copy ledger snapshots to USB"],
      fear: "Being blamed for the fraud he discovered",
      relationships: { "Daniel Pierce": "Mentor", "Marcus Webb": "Fears retaliation" },
      financialSituation: "Student loans, modest savings",
      dailyRoutine: "Last to leave accounting floor",
      motive: "None — Pierce was his protector",
      alibi: "Uber drop-off at apartment 10:18 PM, roommate confirms",
      truthfulness: 8,
      behavior: "Nervous, over-explains details",
      speechStyle: "Hesitant, technical accounting terms",
      knowledge: ["Found duplicate vendor payments in Q3", "Pierce told him 'Monday changes everything'"],
      memory: {},
      isGuilty: false,
    }),
  ],
  witnesses: [
    witness({
      id: "witness-guard",
      name: "Samuel Drake",
      age: 56,
      occupation: "Night Security Supervisor",
      personality: "By-the-book, tired",
      stressLevel: 4,
      intelligence: 6,
      secrets: [],
      fear: "Losing pension over missed protocol",
      relationships: {},
      financialSituation: "Stable",
      dailyRoutine: "Monitors garage cameras from booth",
      motive: "N/A",
      alibi: "On duty entire shift",
      truthfulness: 9,
      behavior: "Formal, reads from incident notes",
      speechStyle: "Flat procedural report tone",
      knowledge: [
        "Saw a silver sedan exit P3 ramp at 11:05 PM — plate partially obscured",
        "Marcus Webb's Tesla badge-swipe recorded 10:58 PM at garage entry",
        "Heard shouting on P3 around 10:50 PM",
      ],
      memory: {},
    }),
  ],
  evidence: [
    evidence({
      id: "ev-fir",
      title: "First Information Report",
      type: "document",
      description: "Initial homicide report filed by responding officers.",
      locationFound: "Detective Bureau",
      discoveredByDefault: true,
      hidden: false,
      relatedPeople: ["victim-pierce"],
      relatedEvidence: [],
      significance: "supporting",
      tags: ["official"],
      documentId: "doc-fir",
    }),
    evidence({
      id: "ev-briefcase",
      title: "Bloodied Briefcase",
      type: "physical",
      description: "Leather briefcase with Pierce's prints and a dent matching a tire iron. Contains printed ledger anomalies.",
      locationFound: "P3 parking space 314",
      discoveredByDefault: true,
      hidden: false,
      relatedPeople: ["victim-pierce", "suspect-webb"],
      relatedEvidence: ["ev-ledger"],
      significance: "critical",
      tags: ["weapon", "financial"],
      image: "/images/evidence-01-briefcase.png",
    }),
    evidence({
      id: "ev-ledger",
      title: "Ledger Anomaly Printout",
      type: "financial",
      description: "$2.3M routed through vendor 'Northline Consulting' — shell company linked to Webb's personal email domain.",
      locationFound: "Inside briefcase",
      discoveredByDefault: true,
      hidden: false,
      relatedPeople: ["victim-pierce", "suspect-webb"],
      relatedEvidence: ["ev-briefcase", "ev-bank"],
      significance: "critical",
      tags: ["financial", "motive"],
    }),
    evidence({
      id: "ev-badge",
      title: "Garage Badge Swipe Log",
      type: "digital",
      description: "Marcus Webb entered garage 10:58 PM. No corresponding exit swipe — he used staff vehicle lane.",
      locationFound: "Security server",
      discoveredByDefault: true,
      hidden: false,
      relatedPeople: ["suspect-webb"],
      relatedEvidence: ["ev-cctv"],
      significance: "critical",
      tags: ["alibi", "timeline"],
    }),
    evidence({
      id: "ev-cctv",
      title: "CCTV Gap Footage",
      type: "media",
      description: "Camera P3-B blind spot exploited 10:49–10:54 PM. Tech log shows manual override from executive credential.",
      locationFound: "Security office",
      discoveredByDefault: false,
      hidden: true,
      unlockCondition: "Interview security supervisor",
      relatedPeople: ["suspect-webb"],
      relatedEvidence: ["ev-badge"],
      significance: "important",
      tags: ["timeline"],
      documentId: "doc-cctv",
    }),
    evidence({
      id: "ev-tireiron",
      title: "Tire Iron with Blood",
      type: "forensic",
      description: "Found in dumpster two blocks away. Webb's fingerprints on handle. Pierce's blood on striking end.",
      locationFound: "Alley behind 8th Street",
      discoveredByDefault: false,
      hidden: true,
      unlockCondition: "Search alley after warrant",
      relatedPeople: ["suspect-webb", "victim-pierce"],
      relatedEvidence: ["ev-briefcase"],
      significance: "critical",
      tags: ["weapon", "forensic"],
      image: "/images/evidence-01-tireiron.png",
    }),
    evidence({
      id: "ev-bank",
      title: "Northline Wire Transfers",
      type: "financial",
      description: "Bank records show Northline payments deposited into account opened with Webb's driver's license copy.",
      locationFound: "Subpoena — First National Bank",
      discoveredByDefault: false,
      hidden: true,
      unlockCondition: "Request financial warrant",
      relatedPeople: ["suspect-webb"],
      relatedEvidence: ["ev-ledger"],
      significance: "critical",
      tags: ["financial"],
      documentId: "doc-bank",
    }),
    evidence({
      id: "ev-call",
      title: "Investor Call Recording",
      type: "digital",
      description: "Webb's claimed alibi call lasted 8 minutes, ending 10:22 PM. Not continuous through murder window.",
      locationFound: "Telecom subpoena",
      discoveredByDefault: false,
      hidden: false,
      relatedPeople: ["suspect-webb"],
      relatedEvidence: [],
      significance: "important",
      tags: ["alibi"],
      documentId: "doc-call",
    }),
  ],
  timeline: [
    timelineEvent({
      id: "tl-2230",
      timestamp: "2026-03-14 22:30",
      title: "Pierce leaves executive floor",
      description: "Badge swipe at elevator bank. Carrying briefcase.",
      known: true,
      people: ["victim-pierce"],
      evidence: [],
    }),
    timelineEvent({
      id: "tl-2250",
      timestamp: "2026-03-14 22:50",
      title: "Shouting on P3",
      description: "Security guard hears argument near space 314.",
      known: true,
      people: ["victim-pierce"],
      evidence: ["ev-cctv"],
      conflictWith: [],
    }),
    timelineEvent({
      id: "tl-2258",
      timestamp: "2026-03-14 22:58",
      title: "Webb enters garage",
      description: "Badge swipe at P1 entry gate.",
      known: false,
      people: ["suspect-webb"],
      evidence: ["ev-badge"],
    }),
    timelineEvent({
      id: "tl-2305",
      timestamp: "2026-03-14 23:05",
      title: "Silver sedan exits",
      description: "Vehicle leaves via staff lane without full plate capture.",
      known: false,
      people: ["suspect-webb"],
      evidence: ["ev-cctv"],
    }),
    timelineEvent({
      id: "tl-2352",
      timestamp: "2026-03-14 23:52",
      title: "Body discovered",
      description: "Security patrol finds Pierce unresponsive.",
      known: true,
      people: ["victim-pierce", "witness-guard"],
      evidence: [],
    }),
  ],
  documents: [
    doc({
      id: "doc-fir",
      type: "fir",
      title: "First Information Report",
      referenceNumber: "CF-2026-0314-001",
      date: "2026-03-15",
      author: "Det. Sarah Chen",
      content: firContent("The Meridian Ledger", "CF-2026-0314-001", {
        complainant: "Meridian Tech Security",
        victim: "Daniel Pierce, 44",
        location: "550 Meridian Blvd, Parking P3",
        datetime: "2026-03-14 23:52",
        narrative:
          "Victim located beside vehicle registration DLP-4421. Visible head trauma. Briefcase present. No witnesses to assault. SEC audit scheduled 2026-03-17.",
      }),
    }),
    doc({
      id: "doc-autopsy",
      type: "autopsy",
      title: "Autopsy Report — Pierce",
      referenceNumber: "ME-2026-1182",
      date: "2026-03-15",
      author: "Dr. Elena Marsh",
      content: autopsyContent("Daniel Pierce", {
        ref: "ME-2026-1182",
        date: "2026-03-15",
        cause: "Blunt force trauma — cranial hemorrhage",
        timeOfDeath: "Between 22:45 and 23:15",
        findings: [
          "Single impact consistent with cylindrical metal object",
          "Defensive injuries on forearms",
          "No substances detected in toxicology screen",
        ],
      }),
    }),
    doc({
      id: "doc-cctv",
      type: "cctv_log",
      title: "CCTV Override Log",
      referenceNumber: "SEC-OV-0314",
      date: "2026-03-15",
      author: "Samuel Drake",
      content: `CAMERA OVERRIDE LOG — P3-B
Time: 22:49:12 — 22:54:03
Credential: EXEC-001 (Marcus Webb)
Reason field: EMPTY
Restored automatically at 22:54:03`,
      classified: true,
    }),
    doc({
      id: "doc-bank",
      type: "bank_transactions",
      title: "Northline Consulting Transfers",
      referenceNumber: "BNK-SUB-8821",
      date: "2026-03-16",
      author: "Financial Crimes Unit",
      content: `Account ****7712 opened 2024-11-03
ID on file: M. Webb DL copy
Deposits from Meridian vendor payments: $2,314,880.00
Last withdrawal: 2026-03-13 — $400,000 wire to offshore trust`,
      classified: true,
    }),
    doc({
      id: "doc-call",
      type: "phone_records",
      title: "Webb Investor Call Log",
      referenceNumber: "TEL-4429",
      date: "2026-03-16",
      author: "Telecom Liaison",
      content: `2026-03-14 22:14 — 22:22  Duration 8m 12s  Number +1-650-555-0198
No subsequent calls until 06:41 next morning.`,
    }),
  ],
  locations: [
    {
      id: "loc-garage",
      name: "Meridian Parking P3",
      address: "550 Meridian Blvd",
      description: "Underground executive parking. Crime scene taped at space 314.",
      searchable: true,
      unlocked: true,
      evidenceIds: ["ev-briefcase", "ev-ledger"],
      coordinates: { x: 40, y: 55 },
    },
    {
      id: "loc-alley",
      name: "8th Street Alley",
      address: "Behind Meridian Tower",
      description: "Dumpster area. Requires search warrant.",
      searchable: true,
      unlocked: false,
      evidenceIds: ["ev-tireiron"],
      coordinates: { x: 62, y: 48 },
    },
    {
      id: "loc-security",
      name: "Security Office",
      address: "Meridian Lobby B1",
      description: "CCTV servers and badge logs.",
      searchable: true,
      unlocked: true,
      evidenceIds: ["ev-badge", "ev-cctv"],
      coordinates: { x: 28, y: 60 },
    },
  ],
  policeNotes:
    "Pierce was 72 hours from blowing the whistle on Webb. Treat the investor call alibi as priority one. Klein is scared — protective detail may help him open up.",
  redHerrings: ["ev-call"],
  hiddenClues: ["ev-cctv", "ev-tireiron", "ev-bank"],
  evidenceRelationships: [
    { from: "ev-ledger", to: "suspect-webb", label: "shell vendor link", suggested: true },
    { from: "ev-badge", to: "tl-2258", label: "places at scene", suggested: true },
    { from: "ev-tireiron", to: "ev-briefcase", label: "matching weapon", suggested: true },
  ],
  solution: {
    guiltyPartyId: "suspect-webb",
    method: "Bludgeoned Pierce with tire iron during confrontation over audit disclosure",
    motive: "Prevent exposure of $2.3M embezzlement before federal audit",
    opportunity: "Executive garage access, disabled camera, alone with victim on P3",
    requiredEvidence: ["ev-ledger", "ev-badge", "ev-tireiron", "ev-bank"],
    criticalContradictions: ["tl-2258"],
    timelineKey: ["tl-2250", "tl-2258", "tl-2305"],
    charges: ["Murder in the First Degree", "Evidence Tampering", "Securities Fraud"],
  },
});
