import {
  autopsyContent,
  defineCase,
  doc,
  evidence,
  firContent,
  suspect,
  timelineEvent,
  victim,
  witness,
} from "./builder";

/** Inspired by arson-for-profit and business fire homicide cases. Fully fictional. */
export const case04AshAndEmbers = defineCase(4, {
  meta: {
    id: "case-04-ash-embers",
    title: "Ash and Embers",
    crimeType: "Homicide — Arson / Smoke Inhalation",
    severity: "critical",
    date: "2026-02-03",
    time: "2:14 AM",
    location: "Holt Textile Factory, 900 Industrial Way",
    difficulty: "hard",
    synopsis:
      "A factory fire kills the owner inside a locked office. Investigators find two fires — one for money, one for murder.",
    briefing:
      "James Holt was found dead in his second-floor office after a fire consumed the Holt Textile Factory. Arson dogs flag accelerant at two origin points. Insurance had just doubled. A former partner stood to gain from a disputed land clause. Determine if Holt died in the fire or was killed first — and who struck the match.",
    inspiredBy:
      "Inspired by documented arson-for-profit schemes and business partner homicides. All persons and events are fictional.",
    estimatedMinutes: 55,
    coverImage: "/images/case-04-ash-embers.png",
  },
  victim: victim({
    id: "victim-holt",
    name: "James Holt",
    age: 58,
    occupation: "Owner, Holt Textile Factory",
    background:
      "Third-generation textile manufacturer. Refused to sell riverfront land to development group. Had argued with ex-partner day before fire.",
    lastSeen: "6:00 PM leaving accountant's office",
    causeOfDeath: "Smoke inhalation — but pre-mortem head trauma",
    injuries: ["Subdural hematoma before fire", "Hands bound with zip ties", "Accelerant on clothing"],
  }),
  suspects: [
    suspect({
      id: "suspect-grayson",
      name: "Nathan Grayson",
      age: 49,
      occupation: "Former Business Partner",
      personality: "Bitter, strategic, vindictive",
      stressLevel: 8,
      intelligence: 8,
      secrets: [
        "Partnership dissolution gave him 20% of insurance if property destroyed",
        "Was on factory grounds 1:30 AM per ankle monitor glitch",
      ],
      fear: "Losing custody battle — needs cash from clause",
      relationships: { "James Holt": "Ex-partner — lawsuit pending", "Rita Soren": "Paid her for inside access" },
      financialSituation: "Bankrupt, owes developers $1.2M",
      dailyRoutine: "Consulting job by day, drinks by night",
      motive: "Insurance clause + riverfront sale unlocks if factory destroyed",
      alibi: "Claims home alone watching game — neighbor heard TV, not him",
      truthfulness: 3,
      behavior: "Lawyer present, cites litigation history",
      speechStyle: "Cold, legalistic, blames Holt for betrayal",
      knowledge: [
        "Knew office had interior deadbolt only Holt used",
        "Purchased gasoline canister Feb 1",
        "Holt emailed him 'I know what you did to the books' Tuesday",
      ],
      memory: {},
      isGuilty: true,
    }),
    suspect({
      id: "suspect-soren",
      name: "Rita Soren",
      age: 33,
      occupation: "Night Security Contractor",
      personality: "Nervous, easily bought",
      stressLevel: 9,
      intelligence: 5,
      secrets: ["Disabled perimeter camera sector 4 for $2,000 cash", "Let Grayson in side gate"],
      fear: "Prison, losing daughter",
      relationships: { "Nathan Grayson": "Paid her", "James Holt": "Employer" },
      financialSituation: "Single mother, behind on rent",
      dailyRoutine: "Patrols factory 10 PM–6 AM",
      motive: "Accessory — payment for camera disable",
      alibi: "On duty — falsified patrol log shows office check at 1:00 AM",
      truthfulness: 4,
      behavior: "Cracks under pressure about cash deposit",
      speechStyle: "Simple, defensive, repetitive",
      knowledge: [
        "Grayson wore black coveralls and carried metal case",
        "Heard thud from upstairs before smell of smoke",
        "Holt's car was still in lot at 1:45 AM — unusual",
      ],
      memory: {},
      isGuilty: false,
    }),
    suspect({
      id: "suspect-adebayo",
      name: "Dr. Priya Adebayo",
      age: 44,
      occupation: "Insurance Adjuster",
      personality: "Analytical, detached",
      stressLevel: 3,
      intelligence: 9,
      secrets: ["Flagged Holt policy for fraud review day before fire"],
      fear: "Professional reprisal",
      relationships: { "James Holt": "Professional — recent dispute over claim" },
      financialSituation: "Comfortable",
      dailyRoutine: "Desk work, site inspections",
      motive: "None — would lose commission on flagged policy",
      alibi: "Hotel conference 200 miles away — confirmed",
      truthfulness: 9,
      behavior: "Cooperative, provides policy documents",
      speechStyle: "Insurance terminology, dry",
      knowledge: [
        "Policy doubled after Grayson clause triggered Oct revision",
        "Holt threatened to expose staged inventory losses",
        "Accelerant pattern matches amateur pour — not professional arsonist",
      ],
      memory: {},
      isGuilty: false,
    }),
  ],
  witnesses: [
    witness({
      id: "witness-kowalski",
      name: "Frank Kowalski",
      age: 62,
      occupation: "Retired Fire Marshal",
      personality: "Blunt, experienced",
      stressLevel: 2,
      intelligence: 8,
      secrets: [],
      fear: "N/A",
      relationships: {},
      financialSituation: "Pension",
      dailyRoutine: "Consults on suspicious fires",
      motive: "N/A",
      alibi: "Called to scene 2:30 AM",
      truthfulness: 10,
      behavior: "Walks you through burn patterns",
      speechStyle: "Fire science jargon, confident",
      knowledge: [
        "Two origin points — loading bay (insurance) and office (kill zone)",
        "Office fire started AFTER victim already incapacitated",
        "Pour pattern matches gasoline from doorway inward — trap",
      ],
      memory: {},
    }),
  ],
  evidence: [
    evidence({
      id: "ev4-fir",
      title: "First Information Report",
      type: "document",
      description: "Arson homicide — Holt Factory.",
      locationFound: "Detective Bureau",
      discoveredByDefault: true,
      hidden: false,
      relatedPeople: ["victim-holt"],
      relatedEvidence: [],
      significance: "supporting",
      tags: ["official"],
      documentId: "doc4-fir",
    }),
    evidence({
      id: "ev4-office",
      title: "Office Burn Pattern",
      type: "physical",
      description: "V-shaped accelerant pour from door to desk. Victim at desk, zip-tied. Kill fire separate from loading bay blaze.",
      locationFound: "Second floor office",
      discoveredByDefault: true,
      hidden: false,
      relatedPeople: ["victim-holt"],
      relatedEvidence: ["ev4-accelerant", "ev4-autopsy"],
      significance: "critical",
      tags: ["crime scene", "arson"],
      image: "/images/evidence-04-accelerant.png",
    }),
    evidence({
      id: "ev4-accelerant",
      title: "Gasoline Residue Analysis",
      type: "forensic",
      description: "Premium unleaded with additive matching Grayson's lawn equipment fuel sample.",
      locationFound: "Office floorboards",
      discoveredByDefault: true,
      hidden: false,
      relatedPeople: ["suspect-grayson"],
      relatedEvidence: ["ev4-receipt"],
      significance: "critical",
      tags: ["forensic", "arson"],
      documentId: "doc4-arson",
    }),
    evidence({
      id: "ev4-autopsy",
      title: "Pre-fire Head Trauma",
      type: "forensic",
      description: "Subdural hematoma 2-4 hours before smoke inhalation. Victim unconscious before fire lit.",
      locationFound: "Medical examiner",
      discoveredByDefault: true,
      hidden: false,
      relatedPeople: ["victim-holt"],
      relatedEvidence: ["ev4-office"],
      significance: "critical",
      tags: ["forensic"],
      documentId: "doc4-autopsy",
    }),
    evidence({
      id: "ev4-insurance",
      title: "Insurance Clause 14-B",
      type: "document",
      description: "If factory destroyed, Grayson receives 20% payout ($800K) per dissolved partnership agreement.",
      locationFound: "Insurance file",
      discoveredByDefault: true,
      hidden: false,
      relatedPeople: ["suspect-grayson"],
      relatedEvidence: [],
      significance: "important",
      tags: ["motive", "financial"],
      documentId: "doc4-insurance",
    }),
    evidence({
      id: "ev4-receipt",
      title: "Gas Can Purchase Receipt",
      type: "financial",
      description: "Hardware store receipt Feb 1. Credit card: N. Grayson. 5-gallon can + zip ties same transaction.",
      locationFound: "Subpoena",
      discoveredByDefault: false,
      hidden: true,
      unlockCondition: "Financial warrant",
      relatedPeople: ["suspect-grayson"],
      relatedEvidence: ["ev4-accelerant"],
      significance: "critical",
      tags: ["financial"],
      documentId: "doc4-receipt",
    }),
    evidence({
      id: "ev4-camera",
      title: "Disabled Camera Log",
      type: "digital",
      description: "Sector 4 cameras offline 1:25–2:20 AM. Override code entered — Rita Soren credentials.",
      locationFound: "Security server",
      discoveredByDefault: false,
      hidden: true,
      unlockCondition: "Interview security contractor",
      relatedPeople: ["suspect-soren", "suspect-grayson"],
      relatedEvidence: ["ev4-deposit"],
      significance: "important",
      tags: ["timeline"],
      documentId: "doc4-camera",
    }),
    evidence({
      id: "ev4-deposit",
      title: "Soren Cash Deposit",
      type: "financial",
      description: "$2,000 cash deposit Feb 2. Serial numbers match withdrawal from Grayson's account Feb 1.",
      locationFound: "Bank subpoena",
      discoveredByDefault: false,
      hidden: true,
      unlockCondition: "Press Soren on camera gap",
      relatedPeople: ["suspect-soren", "suspect-grayson"],
      relatedEvidence: ["ev4-camera"],
      significance: "important",
      tags: ["financial"],
      documentId: "doc4-deposit",
    }),
    evidence({
      id: "ev4-email",
      title: "Holt's Final Email",
      type: "digital",
      description: "Draft to attorney: 'Grayson cooked inventory numbers. I'm turning files over Friday.' Never sent.",
      locationFound: "Victim's laptop — fire-damaged, recovered",
      discoveredByDefault: false,
      hidden: false,
      relatedPeople: ["suspect-grayson"],
      relatedEvidence: [],
      significance: "important",
      tags: ["motive"],
      documentId: "doc4-email",
    }),
    evidence({
      id: "ev4-monitor",
      title: "Ankle Monitor GPS Glitch",
      type: "digital",
      description: "Grayson's court monitor shows 'signal loss' 1:28–2:05 AM near Industrial Way — not at home.",
      locationFound: "Probation department",
      discoveredByDefault: false,
      hidden: true,
      unlockCondition: "Request probation records",
      relatedPeople: ["suspect-grayson"],
      relatedEvidence: ["ev4-camera"],
      significance: "critical",
      tags: ["alibi"],
      documentId: "doc4-monitor",
    }),
  ],
  timeline: [
    timelineEvent({
      id: "tl4-1800",
      timestamp: "2026-02-02 18:00",
      title: "Holt leaves accountant",
      description: "Last public sighting.",
      known: true,
      people: ["victim-holt"],
      evidence: [],
    }),
    timelineEvent({
      id: "tl4-0130",
      timestamp: "2026-02-03 01:30",
      title: "Grayson on factory grounds",
      description: "Ankle monitor glitch places him at Industrial Way.",
      known: false,
      people: ["suspect-grayson"],
      evidence: ["ev4-monitor"],
    }),
    timelineEvent({
      id: "tl4-0145",
      timestamp: "2026-02-03 01:45",
      title: "Holt's car in lot",
      description: "Soren notes victim returned — unusual hour.",
      known: false,
      people: ["victim-holt"],
      evidence: ["ev4-email"],
    }),
    timelineEvent({
      id: "tl4-0214",
      timestamp: "2026-02-03 02:14",
      title: "Fire reported",
      description: "Loading bay smoke first, then office flashover.",
      known: true,
      people: ["victim-holt"],
      evidence: ["ev4-office"],
    }),
  ],
  documents: [
    doc({
      id: "doc4-fir",
      type: "fir",
      title: "First Information Report",
      referenceNumber: "CF-2026-0203-012",
      date: "2026-02-03",
      author: "Det. Ray Morrison",
      content: firContent("Ash and Embers", "CF-2026-0203-012", {
        complainant: "Fire Department Battalion 7",
        victim: "James Holt, 58",
        location: "900 Industrial Way",
        datetime: "2026-02-03 02:14",
        narrative:
          "Structure fire, victim located in locked office. Arson suspected at two points. ATF notified.",
      }),
    }),
    doc({
      id: "doc4-autopsy",
      type: "autopsy",
      title: "Autopsy — Holt",
      referenceNumber: "ME-2026-0891",
      date: "2026-02-04",
      author: "Dr. Elena Marsh",
      content: autopsyContent("James Holt", {
        ref: "ME-2026-0891",
        date: "2026-02-04",
        cause: "Smoke inhalation — homicide",
        timeOfDeath: "Head trauma ~01:50 AM; fire death ~02:10 AM",
        findings: [
          "Subdural hematoma — blunt object, pre-fire",
          "Zip tie marks on wrists",
          "Accelerant on shirt consistent with gasoline",
          "Victim was alive but unconscious when fire started",
        ],
      }),
      image: "/images/evidence-04-accelerant.png",
    }),
    doc({
      id: "doc4-arson",
      type: "lab_report",
      title: "Arson Lab Report",
      referenceNumber: "ATF-2026-044",
      date: "2026-02-05",
      author: "Frank Kowalski, Consultant",
      content: `DUAL ORIGIN CONFIRMED
Origin A: Loading bay — insurance burn, professional spread
Origin B: Office — pour trap from door to desk

Gasoline brand additive matches suspect Grayson's equipment sample.
HINT: Victim was attacked BEFORE fire. Who benefits from Clause 14-B?`,
    }),
    doc({
      id: "doc4-insurance",
      type: "investigation_notes",
      title: "Policy Analysis",
      referenceNumber: "INS-HOLT-2026",
      date: "2026-02-04",
      author: "Dr. Priya Adebayo",
      content: `Policy value: $4,000,000
Clause 14-B: N. Grayson — 20% on total loss event
Riverfront reversion clause activates if factory destroyed
Policy flagged for fraud review Feb 2 — Holt cooperative`,
    }),
    doc({
      id: "doc4-receipt",
      type: "receipt",
      title: "Hardware Store Transaction",
      referenceNumber: "RCT-88291",
      date: "2026-02-05",
      author: "Subpoena",
      content: `Feb 1, 2026 — Ace Hardware #442
5-gallon gas can: $34.99
Zip ties (heavy duty): $8.49
Card: **** Grayson, Nathan
Time: 19:22`,
      classified: true,
    }),
    doc({
      id: "doc4-camera",
      type: "cctv_log",
      title: "Security Override Log",
      referenceNumber: "SEC-HT-0203",
      date: "2026-02-04",
      author: "Factory IT",
      content: `Sector 4 cameras OFFLINE
01:25:44 — Override by user RSOREN
02:20:11 — System restored
Side gate badge: NONE (manual entry)`,
      classified: true,
    }),
    doc({
      id: "doc4-deposit",
      type: "bank_transactions",
      title: "Cash Trail",
      referenceNumber: "BNK-2026-118",
      date: "2026-02-05",
      author: "Financial Crimes",
      content: `Grayson ATM withdrawal: $2,000 — Feb 1
Soren deposit: $2,000 cash — Feb 2
Bill serial overlap: 17 matching notes`,
      classified: true,
    }),
    doc({
      id: "doc4-email",
      type: "email",
      title: "Recovered Draft Email",
      referenceNumber: "DF-2026-0203",
      date: "2026-02-05",
      author: "Digital Forensics",
      content: `DRAFT — To: attorney@lawfirm.com
Subject: Grayson fraud files
"Nathan cooked inventory for 3 years. I'm handing everything to the AG Friday. He doesn't know I kept the originals."

Last edited: Feb 2, 2026 22:14`,
    }),
    doc({
      id: "doc4-monitor",
      type: "investigation_notes",
      title: "Ankle Monitor Report",
      referenceNumber: "PROB-2026-88",
      date: "2026-02-06",
      author: "Probation Services",
      content: `Subject: Nathan Grayson
Feb 3, 01:28–02:05 — Signal anomaly
Triangulation: 900 Industrial Way (factory)
Home address alibi: NOT CONFIRMED`,
      classified: true,
    }),
  ],
  locations: [
    {
      id: "loc4-factory",
      name: "Holt Textile Factory",
      address: "900 Industrial Way",
      description: "Burned structure. Office on second floor — origin point B.",
      searchable: true,
      unlocked: true,
      evidenceIds: ["ev4-office", "ev4-accelerant"],
      coordinates: { x: 50, y: 45 },
    },
    {
      id: "loc4-office",
      name: "Second Floor Office",
      address: "Factory — East Wing",
      description: "Locked interior deadbolt. Victim's desk, pour pattern.",
      searchable: true,
      unlocked: true,
      evidenceIds: ["ev4-autopsy"],
      coordinates: { x: 55, y: 40 },
    },
    {
      id: "loc4-security",
      name: "Security Trailer",
      address: "Factory Gate",
      description: "Camera logs, Soren's patrol records.",
      searchable: true,
      unlocked: false,
      evidenceIds: ["ev4-camera", "ev4-deposit"],
      coordinates: { x: 40, y: 55 },
    },
  ],
  policeNotes:
    "Dual-origin fire — murder disguised as arson-for-profit. Grayson has motive via Clause 14-B. Soren is the weak link — she heard the thud before smoke. Break her alibi on patrol log.",
  redHerrings: ["suspect-adebayo"],
  hiddenClues: ["ev4-receipt", "ev4-camera", "ev4-deposit", "ev4-monitor"],
  evidenceRelationships: [
    { from: "ev4-insurance", to: "suspect-grayson", label: "payout motive", suggested: true },
    { from: "ev4-autopsy", to: "ev4-office", label: "murder before fire", suggested: true },
    { from: "ev4-deposit", to: "ev4-camera", label: "paid access", suggested: true },
  ],
  solution: {
    guiltyPartyId: "suspect-grayson",
    method: "Bludgeoned Holt in office, zip-tied him, poured gasoline trap, disabled cameras via Soren",
    motive: "Insurance clause payout + silencing fraud exposure",
    opportunity: "Knowledge of office layout, paid security access, purchased accelerant",
    requiredEvidence: ["ev4-office", "ev4-accelerant", "ev4-autopsy", "ev4-monitor", "ev4-receipt"],
    criticalContradictions: ["tl4-0130"],
    timelineKey: ["tl4-0145", "tl4-0214"],
    charges: ["Murder in the First Degree", "Arson", "Conspiracy"],
  },
});
