import {
  defineCase,
  doc,
  evidence,
  firContent,
  suspect,
  timelineEvent,
  victim,
  witness,
} from "./builder";

/** Inspired by historical domestic poisoning cases and caregiver homicide patterns. Fully fictional. */
export const case03LilacRoom = defineCase(3, {
  meta: {
    id: "case-03-lilac-room",
    title: "The Lilac Room",
    crimeType: "Homicide — Acute Poisoning",
    severity: "high",
    date: "2025-11-08",
    time: "9:42 PM",
    location: "Whitmore Estate, 18 Lilac Lane",
    difficulty: "medium",
    synopsis:
      "A philanthropist collapses during her own charity dinner. The wine was poured by someone who knew exactly which glass was hers.",
    briefing:
      "Eleanor Whitmore, 68, collapsed at the head of her dining table during a seated dinner for twelve. Guests describe cyanosis and convulsions. Toxicology flags cardiac glycosides. Family, staff, and a recently changed will are all in play. Pay attention to who poured wine, who benefits, and who had pharmacy access.",
    inspiredBy:
      "Inspired by documented caregiver poisoning cases and inheritance-driven homicides. All characters and events are fictional.",
    estimatedMinutes: 50,
    coverImage: "/images/case-03-lilac-room.png",
  },
  victim: victim({
    id: "victim-whitmore",
    name: "Eleanor Whitmore",
    age: 68,
    occupation: "Philanthropist & Art Patron",
    background:
      "Widow of shipping magnate. Recently revised estate plan to fund a public hospital wing instead of family trust.",
    lastSeen: "9:30 PM seated at head of table, toast in progress",
    causeOfDeath: "Digoxin toxicity — acute cardiac arrest",
    injuries: ["No external trauma", "Bit tongue during seizure", "Lividity consistent with dining chair collapse"],
  }),
  suspects: [
    suspect({
      id: "suspect-hughes",
      name: "Clara Hughes",
      age: 36,
      occupation: "Private Nurse & Live-in Caregiver",
      personality: "Devoted facade, quietly resentful",
      stressLevel: 8,
      intelligence: 8,
      secrets: [
        "Borrowed $90,000 against future inheritance that was removed from will",
        "Stole digoxin from patient's medication stock over two weeks",
      ],
      fear: "Ruin and prison — sole provider for disabled brother",
      relationships: {
        "Eleanor Whitmore": "Employer of 4 years",
        "Victor Whitmore": "Secretly dated briefly — ended badly",
      },
      financialSituation: "Debt from brother's care, no savings",
      dailyRoutine: "Manages medications, escorts Eleanor to events",
      motive: "New will cuts her $200,000 bequest; life insurance policy names her for $50K",
      alibi: "Claims she was in kitchen plating dessert when Eleanor collapsed",
      truthfulness: 3,
      behavior: "Tearful, mentions devotion constantly",
      speechStyle: "Soft, caregiving vocabulary, religious references",
      knowledge: [
        "Knows Eleanor's wine preference — Burgundy, left side placement",
        "Access to medication lockbox",
        "Victor argued with Eleanor about will at 4 PM",
      ],
      memory: {},
      isGuilty: true,
    }),
    suspect({
      id: "suspect-victor",
      name: "Victor Whitmore",
      age: 41,
      occupation: "Estranged Stepson",
      personality: "Entitled, theatrical, in debt",
      stressLevel: 7,
      intelligence: 6,
      secrets: ["Owes $400K to art forgery ring", "Forged Eleanor's signature on loan document"],
      fear: "Creditors who threatened 'accidents'",
      relationships: { "Eleanor Whitmore": "Stepmother — hostile", "Clara Hughes": "Brief affair, leverage" },
      financialSituation: "Bleeding cash, blocked from trust",
      dailyRoutine: "Arrived afternoon of dinner, stayed in east wing",
      motive: "Disinherited by new will signed October 30",
      alibi: "Seated at table foot, multiple witnesses — stood during toast only",
      truthfulness: 5,
      behavior: "Defensive about money, performs grief",
      speechStyle: "Upper-class drawl, dismissive",
      knowledge: ["Will reading scheduled next week", "Saw Clara alone in wine cellar 8:45 PM"],
      memory: {},
      isGuilty: false,
    }),
    suspect({
      id: "suspect-brennan",
      name: "Margaret Brennan",
      age: 55,
      occupation: "Estate Attorney",
      personality: "Ice-cold professional",
      stressLevel: 4,
      intelligence: 9,
      secrets: ["Drafted will knowing it would enrage Victor"],
      fear: "Malpractice if client death ruled suspicious",
      relationships: { "Eleanor Whitmore": "Attorney of 20 years" },
      financialSituation: "Affluent",
      dailyRoutine: "Attended dinner as guest and counsel",
      motive: "None financial — reputation risk only",
      alibi: "Seated right of Eleanor, never left table",
      truthfulness: 9,
      behavior: "Precise, cites estate law",
      speechStyle: "Legalistic, measured",
      knowledge: [
        "Will change leaves hospital foundation 60% of estate",
        "Eleanor complained Clara seemed 'distant' last month",
      ],
      memory: {},
      isGuilty: false,
    }),
  ],
  witnesses: [
    witness({
      id: "witness-chef",
      name: "Antoine Duval",
      age: 48,
      occupation: "Private Chef",
      personality: "Perfectionist, observant",
      stressLevel: 6,
      intelligence: 7,
      secrets: [],
      fear: "Career ruined by scandal",
      relationships: {},
      financialSituation: "Stable",
      dailyRoutine: "Ran kitchen service",
      motive: "N/A",
      alibi: "Kitchen staff confirm presence until collapse",
      truthfulness: 8,
      behavior: "Insists on service timeline precision",
      speechStyle: "French-accented culinary detail",
      knowledge: [
        "Clara brought wine decanter from cellar at 9:15 PM alone",
        "Eleanor's glass was pre-set at seat 1 — left of centerpiece lilacs",
        "Dessert course delayed because Clara was 'checking medications'",
      ],
      memory: {},
    }),
  ],
  evidence: [
    evidence({
      id: "ev3-fir",
      title: "First Information Report",
      type: "document",
      description: "Poisoning homicide — Whitmore Estate.",
      locationFound: "Detective Bureau",
      discoveredByDefault: true,
      hidden: false,
      relatedPeople: ["victim-whitmore"],
      relatedEvidence: [],
      significance: "supporting",
      tags: ["official"],
      documentId: "doc3-fir",
    }),
    evidence({
      id: "ev3-glass",
      title: "Eleanor's Wine Glass",
      type: "physical",
      description: "Burgundy residue. Lip print matches Eleanor. Digoxin concentration 40x therapeutic in remaining dregs.",
      locationFound: "Dining table seat 1",
      discoveredByDefault: true,
      hidden: false,
      relatedPeople: ["victim-whitmore"],
      relatedEvidence: ["ev3-toxicology", "ev3-decanter"],
      significance: "critical",
      tags: ["crime scene", "forensic"],
      image: "/images/evidence-03-wineglass.png",
    }),
    evidence({
      id: "ev3-toxicology",
      title: "Toxicology Screen",
      type: "forensic",
      description: "Blood digoxin 8.2 ng/mL — fatal. No prescribed cardiac medication for Eleanor.",
      locationFound: "Hospital lab",
      discoveredByDefault: true,
      hidden: false,
      relatedPeople: ["victim-whitmore"],
      relatedEvidence: ["ev3-glass"],
      significance: "critical",
      tags: ["forensic"],
      documentId: "doc3-toxicology",
    }),
    evidence({
      id: "ev3-decanter",
      title: "Wine Decanter",
      type: "physical",
      description: "Other glasses show normal wine only. Eleanor's pour came last from decanter — digoxin isolated to final 60ml.",
      locationFound: "Dining sideboard",
      discoveredByDefault: true,
      hidden: false,
      relatedPeople: ["suspect-hughes"],
      relatedEvidence: ["ev3-glass", "ev3-fingerprint"],
      significance: "important",
      tags: ["crime scene"],
    }),
    evidence({
      id: "ev3-fingerprint",
      title: "Decanter Fingerprints",
      type: "forensic",
      description: "Clara Hughes prints on decanter base and stopper. Consistent with server role — but only her handled cellar retrieval.",
      locationFound: "Forensics",
      discoveredByDefault: false,
      hidden: true,
      unlockCondition: "Process dining room evidence",
      relatedPeople: ["suspect-hughes"],
      relatedEvidence: ["ev3-decanter"],
      significance: "important",
      tags: ["forensic"],
    }),
    evidence({
      id: "ev3-medbox",
      title: "Medication Lockbox",
      type: "physical",
      description: "Eleanor's vitamins intact. Empty blister pack of digoxin hidden under liner — caregiver access log shows Hughes opened box 9:00 PM.",
      locationFound: "Eleanor's bedroom",
      discoveredByDefault: false,
      hidden: true,
      unlockCondition: "Search bedroom with warrant",
      relatedPeople: ["suspect-hughes"],
      relatedEvidence: ["ev3-toxicology"],
      significance: "critical",
      tags: ["motive", "forensic"],
    }),
    evidence({
      id: "ev3-will",
      title: "Revised Last Will",
      type: "document",
      description: "Signed Oct 30. Hospital foundation primary beneficiary. Clara's $200K bequest struck. Victor disinherited.",
      locationFound: "Brennan law offices",
      discoveredByDefault: true,
      hidden: false,
      relatedPeople: ["suspect-hughes", "suspect-victor"],
      relatedEvidence: [],
      significance: "important",
      tags: ["motive"],
      documentId: "doc3-will",
    }),
    evidence({
      id: "ev3-insurance",
      title: "Caregiver Life Insurance",
      type: "financial",
      description: "Policy on Eleanor's life — $50,000 beneficiary Clara Hughes, taken without Eleanor's knowledge.",
      locationFound: "Insurance subpoena",
      discoveredByDefault: false,
      hidden: true,
      unlockCondition: "Financial records warrant",
      relatedPeople: ["suspect-hughes"],
      relatedEvidence: ["ev3-will"],
      significance: "critical",
      tags: ["motive", "financial"],
      documentId: "doc3-insurance",
    }),
    evidence({
      id: "ev3-debt",
      title: "Clara's Loan Documents",
      type: "financial",
      description: "$90,000 personal loan collateralized against 'expected inheritance' — dated before will revision.",
      locationFound: "Bank subpoena",
      discoveredByDefault: false,
      hidden: true,
      unlockCondition: "Interview Victor about Clara",
      relatedPeople: ["suspect-hughes"],
      relatedEvidence: ["ev3-will"],
      significance: "important",
      tags: ["motive"],
      documentId: "doc3-debt",
    }),
    evidence({
      id: "ev3-cctv",
      title: "Cellar Camera Still",
      type: "media",
      description: "8:45 PM — Clara alone in wine cellar 11 minutes. Victor enters briefly at 8:52, leaves without bottles.",
      locationFound: "Estate security",
      discoveredByDefault: false,
      hidden: false,
      relatedPeople: ["suspect-hughes", "suspect-victor"],
      relatedEvidence: ["ev3-decanter"],
      significance: "important",
      tags: ["timeline"],
      documentId: "doc3-cctv",
    }),
  ],
  timeline: [
    timelineEvent({
      id: "tl3-2045",
      timestamp: "2025-11-08 20:45",
      title: "Clara in wine cellar",
      description: "Alone 11 minutes — decanter selected.",
      known: false,
      people: ["suspect-hughes"],
      evidence: ["ev3-cctv"],
    }),
    timelineEvent({
      id: "tl3-2100",
      timestamp: "2025-11-08 21:00",
      title: "Medication lockbox opened",
      description: "Access log — Hughes, bedroom.",
      known: false,
      people: ["suspect-hughes"],
      evidence: ["ev3-medbox"],
    }),
    timelineEvent({
      id: "tl3-2115",
      timestamp: "2025-11-08 21:15",
      title: "Wine service",
      description: "Clara pours from decanter. Eleanor served last.",
      known: true,
      people: ["suspect-hughes", "victim-whitmore"],
      evidence: ["ev3-glass"],
    }),
    timelineEvent({
      id: "tl3-2130",
      timestamp: "2025-11-08 21:30",
      title: "Charity toast",
      description: "Eleanor stands, drinks, begins speech.",
      known: true,
      people: ["victim-whitmore"],
      evidence: [],
    }),
    timelineEvent({
      id: "tl3-2142",
      timestamp: "2025-11-08 21:42",
      title: "Collapse",
      description: "Cardiac arrest at table. Clara performs CPR — poorly.",
      known: true,
      people: ["victim-whitmore", "suspect-hughes"],
      evidence: ["ev3-toxicology"],
    }),
  ],
  documents: [
    doc({
      id: "doc3-fir",
      type: "fir",
      title: "First Information Report",
      referenceNumber: "CF-2025-1108-003",
      date: "2025-11-09",
      author: "Det. Amara Okonkwo",
      content: firContent("The Lilac Room", "CF-2025-1108-003", {
        complainant: "Margaret Brennan (attorney)",
        victim: "Eleanor Whitmore, 68",
        location: "18 Lilac Lane, Dining Hall",
        datetime: "2025-11-08 21:42",
        narrative:
          "Victim collapsed during dinner party of 12. EMS unable to revive. Hospital suspected poisoning. Estate recently revised.",
      }),
    }),
    doc({
      id: "doc3-toxicology",
      type: "lab_report",
      title: "Toxicology Report",
      referenceNumber: "LAB-2025-9912",
      date: "2025-11-09",
      author: "Metro Forensic Lab",
      content: `SUBJECT: Eleanor Whitmore
DIGOXIN (blood): 8.2 ng/mL — FATAL
DIGOXIN (wine residue): Present in glass #1 only
PRESCRIPTION STATUS: Victim NOT prescribed digoxin

NOTE: Digoxin is bitter. Wine masks bitterness effectively.
HINT: Only one glass was poisoned. Who poured last?`,
      image: "/images/evidence-03-wineglass.png",
    }),
    doc({
      id: "doc3-will",
      type: "investigation_notes",
      title: "Estate Summary",
      referenceNumber: "EST-2025-WHIT",
      date: "2025-11-10",
      author: "Margaret Brennan",
      content: `REVISED WILL — Executed Oct 30, 2025
Primary: Whitmore Memorial Hospital Foundation (60%)
Victor Whitmore: DISINHERITED
Clara Hughes bequest: REMOVED (previously $200,000)
Staff annuities: unchanged`,
    }),
    doc({
      id: "doc3-insurance",
      type: "investigation_notes",
      title: "Unauthorized Insurance Policy",
      referenceNumber: "INS-2025-441",
      date: "2025-11-11",
      author: "Financial Crimes",
      content: `Policy #LIF-8839201 on Eleanor Whitmore
Beneficiary: Clara Hughes — $50,000
Premium payer: Clara Hughes (cash)
Insured signature: FORGED (graphology pending)
Application date: Sept 12, 2025`,
      classified: true,
    }),
    doc({
      id: "doc3-debt",
      type: "bank_transactions",
      title: "Hughes Loan File",
      referenceNumber: "BNK-2025-220",
      date: "2025-11-11",
      author: "Subpoena Response",
      content: `Borrower: Clara Hughes — $90,000
Stated collateral: "Whitmore estate bequest"
Loan date: Aug 3, 2025 (before will revision)
Notes: Borrower told loan officer bequest was "guaranteed"`,
      classified: true,
    }),
    doc({
      id: "doc3-cctv",
      type: "cctv_log",
      title: "Wine Cellar Camera Log",
      referenceNumber: "EST-CAM-12",
      date: "2025-11-09",
      author: "Estate Security",
      content: `20:45:12 — C. Hughes enters cellar
20:56:08 — C. Hughes exits with decanter
20:52:30 — V. Whitmore enters, exits 20:53:01 (no bottles)
21:15:00 — Dining service begins`,
    }),
  ],
  locations: [
    {
      id: "loc3-dining",
      name: "Lilac Dining Hall",
      address: "Whitmore Estate",
      description: "Twelve-seat table, lilac centerpiece, crime scene preserved.",
      searchable: true,
      unlocked: true,
      evidenceIds: ["ev3-glass", "ev3-decanter"],
      coordinates: { x: 45, y: 50 },
    },
    {
      id: "loc3-bedroom",
      name: "Eleanor's Bedroom",
      address: "Whitmore Estate — East Wing",
      description: "Medication lockbox, will draft copies.",
      searchable: true,
      unlocked: false,
      evidenceIds: ["ev3-medbox"],
      coordinates: { x: 60, y: 35 },
    },
    {
      id: "loc3-cellar",
      name: "Wine Cellar",
      address: "Whitmore Estate — Basement",
      description: "Camera coverage, decanter storage.",
      searchable: true,
      unlocked: true,
      evidenceIds: ["ev3-cctv"],
      coordinates: { x: 35, y: 65 },
    },
  ],
  policeNotes:
    "Classic inheritance poisoning pattern. Victor looks guilty on paper but twelve witnesses had eyes on him. Clara had pharmacy access, poured wine, and lost the bequest. Get the lockbox and insurance policy.",
  redHerrings: ["suspect-victor"],
  hiddenClues: ["ev3-medbox", "ev3-insurance", "ev3-debt", "ev3-fingerprint"],
  evidenceRelationships: [
    { from: "ev3-glass", to: "ev3-toxicology", label: "poison confirmed", suggested: true },
    { from: "ev3-will", to: "suspect-hughes", label: "lost inheritance", suggested: true },
    { from: "ev3-medbox", to: "ev3-toxicology", label: "source identified", suggested: true },
  ],
  solution: {
    guiltyPartyId: "suspect-hughes",
    method: "Stole digoxin from medication stock, added to Eleanor's wine pour during service",
    motive: "Removed bequest, secret insurance payout, loan collateral destroyed",
    opportunity: "Sole cellar access for decanter, medication access, poured victim's glass",
    requiredEvidence: ["ev3-glass", "ev3-toxicology", "ev3-medbox", "ev3-insurance"],
    criticalContradictions: ["tl3-2100"],
    timelineKey: ["tl3-2115", "tl3-2142"],
    charges: ["Murder in the First Degree", "Forgery", "Insurance Fraud"],
  },
});
