import {
  autopsyContent,
  defineCase,
  doc,
  evidence,
  firContent,
  suspect,
  timelineEvent,
  victim,
  witness,
} from "./builder";

/** Inspired by harbor smuggling murders and dockworker disappearances. Fully fictional. */
export const case02BloodTide = defineCase(2, {
  meta: {
    id: "case-02-blood-tide",
    title: "Blood Tide",
    crimeType: "Homicide — Asphyxiation / Concealed Body",
    severity: "critical",
    date: "2026-01-22",
    time: "05:18 AM",
    location: "Redhook Container Terminal, Berth 7",
    difficulty: "medium",
    synopsis:
      "A dockworker is found dead inside a sealed shipping container. The tide log says the killer couldn't have been where they claim.",
    briefing:
      "Tommy Reyes, night loader at Redhook Terminal, was found crammed behind cargo pallets in Container RH-4481. The seal was intact from the outside — but someone opened it from inside during the night. Smuggling rumors have plagued Berth 7 for years. Cross-reference tide tables, container manifests, and dock access logs.",
    inspiredBy:
      "Inspired by real harbor smuggling rings and dock homicide patterns documented in port cities worldwide. All persons and events are fictional.",
    estimatedMinutes: 45,
    coverImage: "/images/case-02-blood-tide.png",
  },
  victim: victim({
    id: "victim-reyes",
    name: "Tommy Reyes",
    age: 34,
    occupation: "Night Shift Loader, Redhook Terminal",
    background:
      "Army veteran. Known for keeping a pocket notebook of irregular shipments. Recently asked Internal Affairs for a meeting.",
    lastSeen: "01:40 AM on CCTV entering Break Room B",
    causeOfDeath: "Manual strangulation with rope fiber",
    injuries: ["Ligature marks on neck", "Broken fingers — defensive", "Contusion on temple from blunt object"],
  }),
  suspects: [
    suspect({
      id: "suspect-calloway",
      name: "Frank Calloway",
      age: 52,
      occupation: "Harbor Supervisor, Berth 7",
      personality: "Bullying, territorial, veteran dock boss",
      stressLevel: 9,
      intelligence: 7,
      secrets: ["Runs off-book container inspections for cash", "Reyes caught him bypassing customs scans"],
      fear: "Federal trafficking charges",
      relationships: { "Tommy Reyes": "Employee he threatened twice", "Dina Volkov": "Smuggling contact" },
      financialSituation: "Mortgage underwater, sudden boat payments",
      dailyRoutine: "Patrols Berth 7 11 PM–6 AM",
      motive: "Reyes was about to report altered manifest weights to Coast Guard liaison",
      alibi: "Claims he was in supervisor shack on phone with union rep 1:00–3:00 AM",
      truthfulness: 2,
      behavior: "Aggressive, challenges authority of detectives",
      speechStyle: "Gruff maritime slang, short sentences",
      knowledge: [
        "Knows container RH-4481 held 'machine parts' that smelled like chemicals",
        "Has master bolt cutter in shack — recently wiped",
        "Volkswagen registered to his nephew was on dock that night",
      ],
      memory: {},
      isGuilty: true,
    }),
    suspect({
      id: "suspect-volkov",
      name: "Dina Volkov",
      age: 38,
      occupation: "Freight Broker",
      personality: "Calculating, charming, evasive",
      stressLevel: 6,
      intelligence: 9,
      secrets: ["Routes contraband through Calloway's berth for 15% cut"],
      fear: "Deportation and losing custody of daughter",
      relationships: { "Frank Calloway": "Business partner in smuggling", "Tommy Reyes": "Feared he recognized her manifests" },
      financialSituation: "Luxury apartment, cash deposits",
      dailyRoutine: "Emails manifests from home office, visits dock at shift change",
      motive: "Shipment exposure would end her brokerage license",
      alibi: "Home IP logs show email activity 12:30–4:00 AM",
      truthfulness: 4,
      behavior: "Polite, lawyer on speed dial",
      speechStyle: "Corporate shipping jargon, slight accent",
      knowledge: ["RH-4481 manifest lists false weight by 2 tons", "Calloway texted 'handle the notebook guy'"],
      memory: {},
      isGuilty: false,
    }),
    suspect({
      id: "suspect-huang",
      name: "James Huang",
      age: 41,
      occupation: "Crane Operator",
      personality: "Quiet, observant, union loyalist",
      stressLevel: 5,
      intelligence: 7,
      secrets: ["Saw Calloway near RH-4481 at 2:10 AM but fears retaliation"],
      fear: "Blacklisted from every port on East Coast",
      relationships: { "Tommy Reyes": "Friend from union meetings", "Frank Calloway": "Distrusts him" },
      financialSituation: "Stable union wages",
      dailyRoutine: "Operates Crane 3 midnight to 8 AM",
      motive: "None — Reyes was his union brother",
      alibi: "Crane cab GPS and union timecard confirm location",
      truthfulness: 8,
      behavior: "Reluctant witness, opens up about Calloway if reassured",
      speechStyle: "Sparse, practical, long pauses",
      knowledge: [
        "Heard argument at container row at 2:05 AM",
        "Calloway's shack light was on at 2:15 AM — not on union call",
        "Reyes showed him a photo of altered seals last week",
      ],
      memory: {},
      isGuilty: false,
    }),
  ],
  witnesses: [
    witness({
      id: "witness-morales",
      name: "Elena Morales",
      age: 29,
      occupation: "Coast Guard Port Inspector",
      personality: "Methodical, by-the-book",
      stressLevel: 3,
      intelligence: 8,
      secrets: [],
      fear: "N/A",
      relationships: { "Tommy Reyes": "Had scheduled meeting with him Friday" },
      financialSituation: "Government salary",
      dailyRoutine: "Inspects manifests 6 AM daily",
      motive: "N/A",
      alibi: "Off duty until 5:30 AM",
      truthfulness: 9,
      behavior: "Professional, provides tide and seal expertise",
      speechStyle: "Regulation citations, precise",
      knowledge: [
        "RH-4481 seal number didn't match manifest photo from prior scan",
        "High tide at 2:38 AM would flood container if door open seaward",
        "Reyes emailed her photos of corroded seals Tuesday",
      ],
      memory: {},
    }),
  ],
  evidence: [
    evidence({
      id: "ev2-fir",
      title: "First Information Report",
      type: "document",
      description: "Homicide report — container discovery.",
      locationFound: "Detective Bureau",
      discoveredByDefault: true,
      hidden: false,
      relatedPeople: ["victim-reyes"],
      relatedEvidence: [],
      significance: "supporting",
      tags: ["official"],
      documentId: "doc2-fir",
    }),
    evidence({
      id: "ev2-container",
      title: "Container RH-4481 Crime Scene",
      type: "physical",
      description: "Victim found behind pallet stack. Interior door bolts scratched from inside. Rope fibers on neck match dock hawser.",
      locationFound: "Berth 7, Row C",
      discoveredByDefault: true,
      hidden: false,
      relatedPeople: ["victim-reyes"],
      relatedEvidence: ["ev2-rope", "ev2-seal"],
      significance: "critical",
      tags: ["crime scene"],
      image: "/images/evidence-02-container.png",
    }),
    evidence({
      id: "ev2-notebook",
      title: "Reyes Pocket Notebook",
      type: "physical",
      description: "Water-damaged notebook. Entry: 'FC let RH-4481 through w/o scan 1/20. Weight off by 2T. Photos sent to EM.'",
      locationFound: "Victim's jacket",
      discoveredByDefault: true,
      hidden: false,
      relatedPeople: ["victim-reyes", "suspect-calloway"],
      relatedEvidence: ["ev2-manifest"],
      significance: "critical",
      tags: ["motive", "hint"],
    }),
    evidence({
      id: "ev2-tide",
      title: "Tide Chart Analysis",
      type: "document",
      description: "At 2:38 AM high tide, seaward container door could not stay open — killer must have exited landward before 2:20 AM.",
      locationFound: "Coast Guard liaison",
      discoveredByDefault: true,
      hidden: false,
      relatedPeople: [],
      relatedEvidence: ["ev2-alibi"],
      significance: "important",
      tags: ["timeline", "hint"],
      documentId: "doc2-tide",
    }),
    evidence({
      id: "ev2-alibi",
      title: "Union Phone Records",
      type: "digital",
      description: "Calloway's union call ended 1:12 AM. No outbound calls until 4:47 AM. Shack landline used 2:08–2:14 AM.",
      locationFound: "Telecom subpoena",
      discoveredByDefault: false,
      hidden: true,
      unlockCondition: "Interview crane operator Huang",
      relatedPeople: ["suspect-calloway"],
      relatedEvidence: ["ev2-tide"],
      significance: "critical",
      tags: ["alibi"],
      documentId: "doc2-phone",
    }),
    evidence({
      id: "ev2-seal",
      title: "Tampered Container Seal",
      type: "forensic",
      description: "Seal cut and re-crimped with non-standard tool. Metal shavings match bolt cutter in Calloway's shack.",
      locationFound: "RH-4481 door",
      discoveredByDefault: false,
      hidden: true,
      unlockCondition: "Forensic lab analysis",
      relatedPeople: ["suspect-calloway"],
      relatedEvidence: ["ev2-cutter"],
      significance: "critical",
      tags: ["forensic"],
    }),
    evidence({
      id: "ev2-cutter",
      title: "Bolt Cutter Toolmarks",
      type: "forensic",
      description: "Calloway's bolt cutter recently cleaned with solvent. Microscopic seal metal fragments in jaw.",
      locationFound: "Supervisor shack",
      discoveredByDefault: false,
      hidden: true,
      unlockCondition: "Search warrant — supervisor shack",
      relatedPeople: ["suspect-calloway"],
      relatedEvidence: ["ev2-seal"],
      significance: "critical",
      tags: ["forensic", "weapon"],
    }),
    evidence({
      id: "ev2-manifest",
      title: "Altered Manifest RH-4481",
      type: "document",
      description: "Declared weight 8,400 kg. Crane load cell recorded 10,600 kg. Calloway signed inspection waiver.",
      locationFound: "Terminal records",
      discoveredByDefault: false,
      hidden: false,
      relatedPeople: ["suspect-calloway", "suspect-volkov"],
      relatedEvidence: ["ev2-notebook"],
      significance: "important",
      tags: ["financial", "motive"],
      documentId: "doc2-manifest",
    }),
    evidence({
      id: "ev2-rope",
      title: "Hawser Fiber Analysis",
      type: "forensic",
      description: "Neck ligature fibers match Berth 7 hawser #12 — stored in Calloway's locked cage.",
      locationFound: "Medical examiner",
      discoveredByDefault: false,
      hidden: true,
      unlockCondition: "Autopsy complete",
      relatedPeople: ["suspect-calloway"],
      relatedEvidence: ["ev2-container"],
      significance: "critical",
      tags: ["forensic"],
      documentId: "doc2-autopsy",
    }),
    evidence({
      id: "ev2-text",
      title: "Calloway Text to Volkov",
      type: "digital",
      description: "'Notebook guy won't listen. Handling it tonight.' Sent 1:55 AM from Calloway's phone.",
      locationFound: "Phone extraction",
      discoveredByDefault: false,
      hidden: true,
      unlockCondition: "Request phone warrant",
      relatedPeople: ["suspect-calloway"],
      relatedEvidence: ["ev2-notebook"],
      significance: "important",
      tags: ["motive"],
      documentId: "doc2-text",
    }),
  ],
  timeline: [
    timelineEvent({
      id: "tl2-0140",
      timestamp: "2026-01-22 01:40",
      title: "Reyes enters break room",
      description: "Last confirmed sighting on camera.",
      known: true,
      people: ["victim-reyes"],
      evidence: [],
    }),
    timelineEvent({
      id: "tl2-0205",
      timestamp: "2026-01-22 02:05",
      title: "Argument at Row C",
      description: "Huang hears shouting near RH-4481.",
      known: false,
      people: ["victim-reyes", "suspect-calloway"],
      evidence: ["ev2-alibi"],
    }),
    timelineEvent({
      id: "tl2-0215",
      timestamp: "2026-01-22 02:15",
      title: "Supervisor shack occupied",
      description: "Light on. Calloway not on union call.",
      known: false,
      people: ["suspect-calloway"],
      evidence: ["ev2-alibi"],
      conflictWith: ["tl2-union"],
    }),
    timelineEvent({
      id: "tl2-union",
      timestamp: "2026-01-22 01:00",
      title: "Calloway claims union call",
      description: "Alibi: on phone with union rep until 3 AM.",
      known: true,
      people: ["suspect-calloway"],
      evidence: ["ev2-alibi"],
      conflictWith: ["tl2-0215"],
    }),
    timelineEvent({
      id: "tl2-0518",
      timestamp: "2026-01-22 05:18",
      title: "Body discovered",
      description: "Opening crew finds Reyes during container inspection.",
      known: true,
      people: ["victim-reyes"],
      evidence: ["ev2-container"],
    }),
  ],
  documents: [
    doc({
      id: "doc2-fir",
      type: "fir",
      title: "First Information Report",
      referenceNumber: "CF-2026-0122-007",
      date: "2026-01-22",
      author: "Det. Marcus Hale",
      content: firContent("Blood Tide", "CF-2026-0122-007", {
        complainant: "Redhook Terminal Security",
        victim: "Tommy Reyes, 34",
        location: "Berth 7, Container RH-4481",
        datetime: "2026-01-22 05:18",
        narrative:
          "Victim discovered during routine open. Container sealed externally. Victim's notebook references supervisor irregularities. Coast Guard notified.",
      }),
    }),
    doc({
      id: "doc2-autopsy",
      type: "autopsy",
      title: "Autopsy — Reyes",
      referenceNumber: "ME-2026-0441",
      date: "2026-01-23",
      author: "Dr. Elena Marsh",
      content: autopsyContent("Tommy Reyes", {
        ref: "ME-2026-0441",
        date: "2026-01-23",
        cause: "Ligature strangulation",
        timeOfDeath: "Between 02:00 and 02:30 AM",
        findings: [
          "Rope fiber consistent with marine hawser",
          "Temple contusion — possible pistol-whipping before strangulation",
          "Defensive fractures on right hand",
          "Trace diesel fuel on boots — Berth 7 apron",
        ],
      }),
      image: "/images/evidence-02-container.png",
    }),
    doc({
      id: "doc2-tide",
      type: "investigation_notes",
      title: "Tide & Access Analysis",
      referenceNumber: "CG-2026-88",
      date: "2026-01-23",
      author: "Elena Morales, USCG",
      content: `TIDE ANALYSIS — BERTH 7
High tide: 02:38 AM (6.1 ft)
Container RH-4481 orientation: seaward door submerged after 02:25 AM

CONCLUSION: Killer exited landward door before 02:20 AM.
Calloway's union call alibi ends 01:12 AM.
Landline in supervisor shack active 02:08–02:14 AM.

HINT: The tide doesn't lie. Cross-reference shack phone.`,
    }),
    doc({
      id: "doc2-phone",
      type: "phone_records",
      title: "Calloway Communications",
      referenceNumber: "TEL-2026-771",
      date: "2026-01-24",
      author: "Financial Crimes Unit",
      content: `MOBILE: Union call ended 01:12:44 AM
SHACK LANDLINE: Outbound 02:08–02:14 AM to RH-4481 row phone
TEXT 01:55 AM to D. Volkov: "Notebook guy won't listen. Handling it tonight."`,
      classified: true,
    }),
    doc({
      id: "doc2-manifest",
      type: "investigation_notes",
      title: "Manifest Discrepancy Report",
      referenceNumber: "RH-MAN-4481",
      date: "2026-01-24",
      author: "Terminal Compliance",
      content: `Container RH-4481
Declared: Machine parts, 8,400 kg
Crane load cell: 10,600 kg
Inspection waiver signed: F. Calloway, 01/20/2026 23:44
Customs scan: BYPASSED`,
    }),
    doc({
      id: "doc2-text",
      type: "chat_history",
      title: "Extracted Text Messages",
      referenceNumber: "EX-2026-0122",
      date: "2026-01-25",
      author: "Digital Forensics",
      content: `FROM: Calloway TO: Volkov 01:55 AM
"Notebook guy won't listen. Handling it tonight."

FROM: Volkov TO: Calloway 01:57 AM
"Don't be stupid."

FROM: Calloway TO: Volkov 04:51 AM
"It's done. Seal is clean."`,
      classified: true,
    }),
  ],
  locations: [
    {
      id: "loc2-berth",
      name: "Berth 7 Container Row",
      address: "Redhook Terminal",
      description: "Crime scene at RH-4481. Salt air, floodlights, crane shadows.",
      searchable: true,
      unlocked: true,
      evidenceIds: ["ev2-container", "ev2-seal"],
      coordinates: { x: 70, y: 40 },
    },
    {
      id: "loc2-shack",
      name: "Supervisor Shack",
      address: "Berth 7 North",
      description: "Calloway's office. Bolt cutter, landline, manifest stamps.",
      searchable: true,
      unlocked: false,
      evidenceIds: ["ev2-cutter", "ev2-alibi"],
      coordinates: { x: 55, y: 35 },
    },
    {
      id: "loc2-crane",
      name: "Crane 3 Cab",
      address: "Berth 7",
      description: "Huang's post. View of Row C.",
      searchable: true,
      unlocked: true,
      evidenceIds: [],
      coordinates: { x: 80, y: 50 },
    },
  ],
  policeNotes:
    "Reyes was a whistleblower. Calloway's union alibi is paper-thin — get shack phone records. Volkov is dirty but her IP alibi holds. Huang knows more than he's saying — offer witness protection.",
  redHerrings: ["suspect-volkov"],
  hiddenClues: ["ev2-alibi", "ev2-cutter", "ev2-rope", "ev2-text"],
  evidenceRelationships: [
    { from: "ev2-tide", to: "ev2-alibi", label: "breaks alibi window", suggested: true },
    { from: "ev2-notebook", to: "suspect-calloway", label: "victim was documenting", suggested: true },
    { from: "ev2-cutter", to: "ev2-seal", label: "toolmatch", suggested: true },
  ],
  solution: {
    guiltyPartyId: "suspect-calloway",
    method: "Lured Reyes to container, strangled with hawser, resealed crate",
    motive: "Silence whistleblower before Coast Guard meeting",
    opportunity: "Supervisor access, bolt cutter, knowledge of tide window",
    requiredEvidence: ["ev2-notebook", "ev2-alibi", "ev2-cutter", "ev2-rope"],
    criticalContradictions: ["tl2-union"],
    timelineKey: ["tl2-0205", "tl2-0215"],
    charges: ["Murder in the Second Degree", "Evidence Tampering", "Smuggling Conspiracy"],
  },
});
